services:
  postgres:
    image: postgres:16
    container_name: hiremenow-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hiremenow
    ports:
      - '5432:5432'
    volumes:
      - hiremenow_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d hiremenow']
      interval: 2s
      timeout: 3s
      retries: 20

  pubsub:
    image: google/cloud-sdk:emulators
    container_name: hiremenow-pubsub
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project=local-project
    ports:
      - '8085:8085'

volumes:
  hiremenow_pgdata:
