config:
  gcp:project: hiremedev
  gcp:region: europe-west1
  hireme-infra:environment: production
  hireme-infra:databaseUrl:
    secure: AAABAEl1vhtxwVBVdkeES6m2aXzMZMXFp1jiv47/HWZucKptgSgXQm2VmsiV3i0gXTqIiiVu+0qUsfrt67zMRba1890AauJBRJSLbAS+wzms8YcaZA9/6J4fSbkG8P2nQpVYP1Eaa6hcD6L/4JVM0wrt56DclIYa
  hireme-infra:jwtSecret:
    secure: AAABALfJtD3RHNQBcwjbXdiUibsE+JbtiPaMQPVvnPb9H/NkmVL5/2Rbwm29T2seHDdYbMMTjWIRWrYeRcLOD8uYn+548gZ2g6I5Bw==
  hireme-infra:openaiApiKey:
    secure: AAABAKNkopPo92LeV2QkWe4PJ1N0hPEKikZ9N/1TRiGst+f/cyT7C2kdLSDVuvd44MoDcocDYDiXdKy7u10Q/XEIGwucyRi5L9cZzy1J4Mrfi54l3f9fFeu5FLUDQR+aBW08txnJqGn3BSGGGGzx9fz8T6DCOepZRP3b/mdBggyeZiC3DNmzvHpyFLdtG9ykh6VOSTzypQv1SOokLGNQqtwa042CJFIn6eKtVxkyPQ5wsfnFdjH0Y6iyrX4NERnVjyu+UQ==
  hireme-infra:cvParserApiKey:
    secure: AAABAGmdjPVBlWfiNOT5pu9ZDl3aMz2NhTu2CK0QryLVDki6M2/ZWE50+CXg34zzHeVsFEsIjwmV8bzbPnMQq+4AWMfpgcvqA+zFviqX6enOvLTr+QMhR4QoMvCRMcCuccxB/nQeRm4QUyULRCvVYMIR+CC6fwBEOLY041dPEOnGY/ZX5PQ8TqCMOXXIDDGTG1cXZMfh6ZZfz7mclhU/Ks99fLDMQMvof+fDCV2smW73ItqsDq1vkovWD4QID47dxhsDdkPpa+rda/km2Q==
  hireme-infra:gcsBucketName: hiremedev
  hireme-infra:allowedOrigins: https://hireme-io.vercel.app
  hireme-infra:cvParserApiUrl: https://api.edenai.run
